# Generated by Django 3.1.12 on 2021-06-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('photos', '0002_photo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cities_light.city', verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cities_light.country', verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
