# Generated by Django 3.1.12 on 2021-06-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20210623_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
