# Generated by Django 3.1.12 on 2021-06-28 15:55

from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20210623_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location',
            field=location_field.models.spatial.LocationField(blank=True, null=True, srid=4326),
        ),
    ]
